### ISSUE TITLE
Empty/Filled stacked Shulker Boxes

### ISSUE THREAD

**Issue by ghost** [FamroFexl/ShulkerLoader#1]
Hello, awesome mod! 🥰
But I found this critical duplication bug if you are able to stack Shulker Boxes.
I hope for a fix - greetings.

**Comment by FamroFexl** [comment]
Thanks for the bug report! I have come up with a few questions that will help me understand. Although I believe it just requires a simple fix, I want the full picture in case I miss anything. 😄

What version of Shulker Loader was used?
What version of Minecraft and which mod loader?
What mod are you using to stack shulker boxes? (also if it is a mod, plugin, resource pack, data pack, or otherwise)
What was the issue specifically? ( i.e. "Did each of the stacked shulker boxes inherit the pickup items?" etc.)

I am assuming this issue only occurred on stacked shulker boxes placed in the offhand. Let me know if otherwise.

**Comment by ghost** [comment]
Latest Mod version - 1.0.5.
Latest Mod Loader - 0.14.9 if I'm correct.
The carpet mod offers the feature to stack Shulker Boxes / AllStackable too.
https://github.com/KrisCris/AllStackable

The feature with stacked Shulker Boxes with the same items comes maybe from a different Carpet extensions, I can check that for you if needed.

If I stack two empty/or filled Shulker Boxes and put them in my offhand slot and catching items up, I have the same items in both Shulker Boxes.

**Comment by FamroFexl** [comment]
I believe the best way to fix this bug would just be to disable dispensing items into the shulker box when it's stack size is greater than one. Other options would likely be unintuitive to the player, especially since this mod wasn't created with that scenario in mind. I should have it fixed in a day or so.

**Comment by ghost** [comment]
Awesome, thanks!

**Comment by FamroFexl** [comment]
New version should be avaliable here on github, modrinth and curseforge.
